name: KitchenGun
version: "1.4.2"
slug: kitchengun
description: Rezeptbuch, Wochenplaner, Chefkoch-Import und Einkaufsliste für Home Assistant.
url: https://github.com/Philosoph89/kitchengun
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
ingress: true
ingress_port: 8099
panel_icon: mdi:chef-hat
panel_title: KitchenGun
homeassistant_api: false
options: {}
schema: {}
